@startuml crud

' https://raw.githubusercontent.com/GC211MP/API/main/documents/crud_matrix.puml

title
  
  =CRUD MATRIX

  |                               |= USER |= DATA |
  |= Add User                     |     C |       |
  |= Load User Data               |     R |       |
  |= Modify User name or password |     U |       |
  | | | |
  |= Give all data                |       |    R  |
  |= Give total distance data     |       |    R  |
  |= Give total calorie data      |       |    R  |
  |= Give total score data        |       |    R  |
  |= Give top score data          |       |    R  |
  |= Enroll rank data             |       |    C  |
  
end title

@enduml
