@startuml crud

' https://raw.githubusercontent.com/GC211MP/API/main/documents/crud_matrix.puml

title
  
  =CRUD MATRIX

  |             |= USER |= DATA |
  |= 사용자 추가   |     C |       |
  |= 사용자 삭제   |     D |   *D  |
  |= 사용자 기록   |     R |    C  |
  
end title



@enduml
