@startuml crud

' https://raw.githubusercontent.com/GC211MP/API/main/documents/crud_matrix.puml

title
  
  =CRUD MATRIX

  |                   |= USER |= DATA |
  |= Add User         |     C |       |
  |= Load User Data   |     R |       |
  |= Modify Name      |     U |       |
  |= Modify Password  |     U |       |
  |= Load rank data   |       |    R  |
  |= Update rank data |     R |    C  |
  
end title



@enduml
