@startuml er-diagram

' https://raw.githubusercontent.com/GC211MP/API/main/documents/erd.puml

left to right direction

title

=[Server] Entity Relationship Diagram

end title

map user {
    <color:red>**(PK)**</color> idx => int
    user_id => varchar(32)
    user_name => varchar(32)
    c_date => DCURRENT_TIMESTAMP
    user_password => varchar(128)
}

map data {
    <color:red>**(PK)**</color> idx => int
    <color:blue>**(FK)**</color> user_idx => int
    c_date => DCURRENT_TIMESTAMP
    stage_id => int
    elapsed_time => int (달린 시간을 초로 저장)
    ? => Float
}

' select * from (select id, name from user) as tmp1
'   join data as data on tmp1.id == data.id;

user ||..o{ data

@enduml
